import { expect, test } from 'vitest'

import { parseYarnLockContent } from './parse'

test('it handles simple dependencies with no duplicates', () => {
  const result = parseYarnLockContent(`
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

"@types/react@*", "@types/react@^18.2.15":
  version "18.2.79"
  resolved "https://registry.yarnpkg.com/@types/react/-/react-18.2.79.tgz#c40efb4f255711f554d47b449f796d1c7756d865"
  integrity sha512-RwGAGXPl9kSXwdNTafkOEuFrTBD5SA2B3iEB96xi8+xu5ddUa/cpvyVCSNn+asgLCTHkb5ZxN8gbuibYJi4s1w==
  dependencies:
    "@types/prop-types" "*"
    csstype "^3.0.2"

react@^18.2.0:
  version "18.2.0"
  resolved "https://registry.yarnpkg.com/react/-/react-18.2.0.tgz#555bd98592883255fa00de14f1151a917b5d77d5"
  integrity sha512-/3IjMdb2L9QbBdWiW5e3P2/npwMBaU9mHCSCUzNln0ZCYbcfTsGbTJrU/kGemdH2IWmB2ioZ+zkxtmq6g09fGQ==
  dependencies:
    loose-envify "^1.1.0"
  `)

  expect(Object.keys(result.dependencies).length).toBe(2)
  expect(result.dependencies['@types/react']).toEqual({
    versions: {
      '18.2.79': ['*', '^18.2.15'],
    },
  })
  expect(result.dependencies['react']).toEqual({
    versions: {
      '18.2.0': ['^18.2.0'],
    },
  })
})

test('it handles multiple versions of the same dependency', () => {
  const result = parseYarnLockContent(`
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

"@types/react@*", "@types/react@^18.2.15":
  version "18.2.79"
  resolved "https://registry.yarnpkg.com/@types/react/-/react-18.2.79.tgz#c40efb4f255711f554d47b449f796d1c7756d865"
  integrity sha512-RwGAGXPl9kSXwdNTafkOEuFrTBD5SA2B3iEB96xi8+xu5ddUa/cpvyVCSNn+asgLCTHkb5ZxN8gbuibYJi4s1w==
  dependencies:
    "@types/prop-types" "*"
    csstype "^3.0.2"

react@^18.2.0:
  version "18.2.0"
  resolved "https://registry.yarnpkg.com/react/-/react-18.2.0.tgz#555bd98592883255fa00de14f1151a917b5d77d5"
  integrity sha512-/3IjMdb2L9QbBdWiW5e3P2/npwMBaU9mHCSCUzNln0ZCYbcfTsGbTJrU/kGemdH2IWmB2ioZ+zkxtmq6g09fGQ==
  dependencies:
    loose-envify "^1.1.0"

react@^7.1.2:
  version "7.1.3"
  resolved "https://registry.yarnpkg.com/react/-/react-18.2.0.tgz#555bd98592883255fa00de14f1151a917b5d77d9"
  integrity sha512-/3IjMdb2L9QbBdWiW5e3P2/npwMBaU9mHCSCUzNln0ZCYbcfTsGbTJrU/kGemdH2IWmB2ioZ+zkxtmq6g09fG7==

react@^18.1.0, react@^18.1.3, react@^18.1.2:
  version "18.1.3"
  resolved "https://registry.yarnpkg.com/react/-/react-18.1.0.tgz#555bd98592883255fa00de14f1151a917b5d77d1"
  integrity sha512-/3IjMdb2L9QbBdWiW5e3P2/npwMBaU9mHCSCUzNln0ZCYbcfTsGbTJrU/kGemdH2IWmB2ioZ+zkxtmq6g09fGV==
  dependencies:
    loose-envify "^1.0.9"
  `)

  expect(Object.keys(result.dependencies).length).toBe(2)
  expect(result.dependencies['@types/react']).toEqual({
    versions: {
      '18.2.79': ['*', '^18.2.15'],
    },
  })
  expect(Object.keys(result.dependencies['react'].versions)).toEqual([
    '7.1.3',
    '18.1.3',
    '18.2.0',
  ])
  expect(result.dependencies['react']).toEqual({
    versions: {
      '7.1.3': ['^7.1.2'],
      '18.1.3': ['^18.1.0', '^18.1.2', '^18.1.3'],
      '18.2.0': ['^18.2.0'],
    },
  })
})
